name = "Iris"
grammar = "iris"
path_suffixes = ["iris"]
line_comments = ["// "]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
]
